"""Add cascading deletes

Revision ID: 3ef7f989db35
Revises: 2d77f5ccefc0
Create Date: 2024-12-14 20:13:53.448388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ef7f989db35'
down_revision = '2d77f5ccefc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referral', schema=None) as batch_op:
        batch_op.drop_constraint('referral_referred_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('referral_referrer_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['referred_user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['referrer_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('task_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_task', schema=None) as batch_op:
        batch_op.drop_constraint('user_task_task_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('user_task_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'task', ['task_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_task_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('user_task_task_id_fkey', 'task', ['task_id'], ['id'])

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('task_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('referral', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('referral_referrer_id_fkey', 'user', ['referrer_id'], ['id'])
        batch_op.create_foreign_key('referral_referred_user_id_fkey', 'user', ['referred_user_id'], ['id'])

    # ### end Alembic commands ###
