"""changed user chat_id field from string back to bigint agn

Revision ID: 46365343acdc
Revises: cfe2fd7383d8
Create Date: 2024-12-12 04:33:57.550738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46365343acdc'
down_revision = 'cfe2fd7383d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('chat_id',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.BigInteger(),
               existing_nullable=True,
               postgresql_using='chat_id::bigint')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('chat_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###
