"""Add URL field to Task model

Revision ID: 89a7429f4c1b
Revises: f0d100ee25f1
Create Date: 2024-12-05 01:06:17.928525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89a7429f4c1b'
down_revision = 'f0d100ee25f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('url', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('url')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
