"""Add user chat id fields for registration

Revision ID: bb7d4be814c2
Revises: a6f8a11d14f5
Create Date: 2024-12-05 07:58:02.240543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb7d4be814c2'
down_revision = 'a6f8a11d14f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_id', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(None, ['chat_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('chat_id')

    # ### end Alembic commands ###
