"""changed user chat_id field from bigit back to string

Revision ID: cfe2fd7383d8
Revises: 9bafc78ce169
Create Date: 2024-12-12 03:45:43.614757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfe2fd7383d8'
down_revision = '9bafc78ce169'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('chat_id',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('chat_id',
               existing_type=sa.String(length=120),
               type_=sa.BIGINT(),
               existing_nullable=True)

    # ### end Alembic commands ###
