"""Change chat_id to BigInteger

Revision ID: fe13d39011aa
Revises: c1d876e33160
Create Date: 2024-12-07 18:50:07.143850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe13d39011aa'
down_revision = 'c1d876e33160'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_task_ids', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('completed_task_ids')

    # ### end Alembic commands ###
